"""``GovernanceInterpreter`` — L3, the behavior→subgoal translation (E17-B).

The single most important new module (handoff §1.3). It takes a
``UserBehaviorEvent`` (what the user did on the GenUI surface) + a
``VMStateSnapshot`` (current VM state) and produces a list of
``SubgoalInstruction`` (what the CUA should execute + how to verify it).

Two translation strategies (handoff §1.3):
  - ``edit_field`` (deterministic): compile_patch(edit, binding) → PatchOps →
    one subgoal per op. The NL is template-derived (per operator + app), using
    visible-content hints from the event payload (NOT GT post_ids). This is
    the "space" strategy — no LLM call, zero latency.
  - ``rollback_to`` (dynamic, strategy B): execution is ``undo_saga`` (the
    proven deterministic mechanism — re-dispatches the inverse op through the
    adapter; for wechat this honestly 409s). The NL DESCRIPTION of what will
    be undone is generated by a lightweight LLM (``complete_json``, non-vision)
    — this is the "time" strategy (handoff §1.3). First-run output is flagged
    ``manual_review_needed=True`` (handoff §6 boundary 3).

Honest design decision (resolved from recon area 7): ``verification_criterion``
is STRUCTURED (an expected_diff-shaped dict or a checkpoint criterion), NOT a
string. The existing verifier (``check_round_trip``) takes a fixture +
snapshots, not a string — a string criterion would be incompatible. The
governance criterion-checker consumes this structured dict.

No-leak boundary: the interpreter receives the user's edit intent (var_id,
new_value) — allowed. It must NOT receive GT old/expected values through the
event. ``verification_criterion`` IS verifier-side GT (consumed by the
verifier, never fed to the CUA prompt) — same boundary as ``expected_diff``.
"""
from __future__ import annotations

import logging
from typing import Any, TYPE_CHECKING

from taskvm.execution.patch_compiler import PatchOp, compile_patch
from taskvm.governance.subgoal import (SubgoalInstruction, WorkflowNode,
                                       WorkflowNodeType, WorkflowPlan)
from tests.fakes.user_behavior_driver import UserBehaviorEvent
from taskvm.governance.vm_state import VMStateSnapshot
from taskvm.governance.checkpoint_graph import CheckpointGraph, CheckpointDirection
# GG.3: SubgoalGenerator replaces the hardcoded _build_edit_nl if/elif templates.
# It emits a zero-internal-id, zero-operator-jargon NL from the visible locator
# (translated control-plane from canonical state).
from tests.fakes.subgoal_generator import instruction_for_op
from taskvm.governance.translate import entity_id_to_locator

if TYPE_CHECKING:
    from taskvm.benchmark.fixtures import CanonicalTaskGraph

logger = logging.getLogger(__name__)


class GovernanceInterpreter:
    """Translate UserBehaviorEvents into SubgoalInstructions (L3)."""

    def __init__(self, *, model: str | None = None,
                 enable_llm_rollback_nl: bool = True,
                 mock_subgoal: bool | None = None) -> None:
        """Args:
          model: the model id for the dynamic rollback NL inference (None →
            TASKVM_DEFAULT_MODEL). Pass a cheaper id for the 'lightweight LLM'
            the handoff describes.
          enable_llm_rollback_nl: if False, skip the LLM call and use a
            deterministic NL template for rollback_to (for mock/offline runs).
          mock_subgoal: GG.3 — if True, the SubgoalGenerator uses its
            deterministic mock path (no LLM); if False, the LLM path. None
            (default) → mirrors ``enable_llm_rollback_nl`` (offline/mock runs
            get the mock path; live runs get the LLM).
        """
        self.model = model
        self.enable_llm_rollback_nl = enable_llm_rollback_nl
        self.mock_subgoal = (enable_llm_rollback_nl if mock_subgoal is None
                             else mock_subgoal)
        self._rollback_nl_seen = 0  # count of LLM-generated rollback NLs (for manual-review flagging)

    # ── main entry ────────────────────────────────────────────────────────
    def interpret(self, event: UserBehaviorEvent,
                  vm_state: VMStateSnapshot,
                  *, task: "CanonicalTaskGraph | None" = None,
                  ) -> list[SubgoalInstruction]:
        """Event + VM state → subgoal list. The ``task`` arg (optional) gives
        the interpreter access to the fixture's checkpoints + expected_diff
        for verification-criterion construction. The scripted + human drivers
        both pass through here transparently."""
        if event.event_type == "edit_field":
            return self._interpret_edit_field(event, vm_state, task)
        if event.event_type == "loop_field":
            # FF.4 §5.3: a loop_field event's template subgoal (the per-event
            # path returns the template; interpret_as_workflow wraps it in a
            # LOOP WorkflowNode for the executor).
            return self._interpret_loop_field(event, vm_state, task)
        if event.event_type in ("set_milestone",):
            return self._interpret_set_milestone(event, vm_state, task)
        if event.event_type == "rollback_to":
            return self._interpret_rollback_to(event, vm_state, task)
        if event.event_type == "checkpoint":
            return self._interpret_checkpoint(event, vm_state)
        if event.event_type == "undo":
            return self._interpret_undo(event, vm_state)
        # should not reach (UserBehaviorEvent validates event_type)
        raise ValueError(f"unhandled event_type {event.event_type!r}")

    # ── edit_field (deterministic) ────────────────────────────────────────
    def _interpret_edit_field(self, event: UserBehaviorEvent,
                              vm_state: VMStateSnapshot,
                              task: "CanonicalTaskGraph | None",
                              ) -> list[SubgoalInstruction]:
        payload = event.payload
        var_id = payload.get("var_id", "")
        new_value = payload.get("new_value", "")
        target_cp = payload.get("target_checkpoint_id")
        if not var_id:
            raise ValueError("edit_field event requires payload['var_id']")
        edit = {"var_id": var_id, "old": payload.get("old_value", ""),
                "new": new_value}
        ops = compile_patch(edit, vm_state.binding)
        subgoals: list[SubgoalInstruction] = []
        for op in ops:
            # GG.3: generate the NL via SubgoalGenerator (zero internal id +
            # zero operator jargon) from the op's visible locator. The locator
            # is translated control-plane from canonical state (the title IS
            # screen-visible → not a GT leak). Replaces _build_edit_nl.
            canonical_entities = self._canonical_for_op(op, vm_state)
            nl, _meta = instruction_for_op(
                op, canonical_entities, mock=self.mock_subgoal, model=self.model)
            criterion = _criterion_for_op(op, task, target_cp, new_value)
            subgoals.append(SubgoalInstruction(
                natural_language=nl,
                patch_ops=[op],
                verification_criterion=criterion,
                source_event_type="edit_field",
                target_checkpoint_id=target_cp,
            ))
        if not subgoals:
            logger.warning("edit_field produced no patch ops for var_id=%s", var_id)
        return subgoals

    def _canonical_for_op(self, op: PatchOp,
                          vm_state: VMStateSnapshot) -> dict[str, dict[str, Any]]:
        """Read the canonical entities for an op's app (control-plane). The
        title field IS screen-visible, so translating entity_id→visible locator
        from this is not a GT leak. Returns {} if the adapter/state is unavailable
        (the SubgoalGenerator then returns the honest cannot-locate sentinel)."""
        ad = (vm_state.adapters or {}).get(op.app)
        if ad is None or not vm_state.sid:
            return {}
        try:
            return ad.read_canonical(vm_state.sid).get("entities", {}) or {}
        except Exception as e:
            logger.warning(f"[interp] read_canonical({op.app}) failed: {e}")
            return {}

    # ── FF.4 §5.3: workflow planner (Sequential / Parallel / Loop) ────────
    def interpret_as_workflow(self, events: list[UserBehaviorEvent],
                              vm_state: VMStateSnapshot,
                              *, task: "CanonicalTaskGraph | None" = None,
                              ) -> WorkflowPlan:
        """Build a WorkflowPlan from a batch of events. Classifies the structure
        (rules, no LLM, zero latency) + wraps subgoals in the right WorkflowNode
        type. The WorkflowExecutor walks the plan's nodes; the existing
        per-event ``interpret()`` is unchanged (for sequential-only tasks)."""
        wf_type = self._classify_workflow(events, task)
        nodes: list[WorkflowNode] = []
        if wf_type == WorkflowNodeType.LOOP:
            for ev in events:
                if ev.event_type == "loop_field":
                    template_sgs = self._interpret_loop_field(ev, vm_state, task)
                    values = list(ev.payload.get("values", []))
                    nodes.append(WorkflowNode(
                        node_type=WorkflowNodeType.LOOP,
                        subgoals=template_sgs, loop_count=len(values),
                        loop_values=values,
                        display_name=str(ev.payload.get("loop_label", "loop")),
                        barrier_label="loop done",
                    ))
                else:
                    sgs = self.interpret(ev, vm_state, task=task)
                    if sgs:
                        nodes.append(WorkflowNode(
                            node_type=WorkflowNodeType.SEQUENTIAL, subgoals=sgs))
        elif wf_type == WorkflowNodeType.PARALLEL:
            # one PARALLEL node: all edit_field subgoals issued concurrently,
            # barrier at the verifier (§5.6 launch_fanout_parallel).
            all_sgs: list[SubgoalInstruction] = []
            for ev in events:
                if ev.event_type == "edit_field":
                    all_sgs.extend(self._interpret_edit_field(ev, vm_state, task))
            if all_sgs:
                nodes.append(WorkflowNode(
                    node_type=WorkflowNodeType.PARALLEL, subgoals=all_sgs,
                    display_name="parallel fanout", barrier_label="verifier"))
        else:   # SEQUENTIAL
            for ev in events:
                sgs = self.interpret(ev, vm_state, task=task)
                if sgs:
                    nodes.append(WorkflowNode(
                        node_type=WorkflowNodeType.SEQUENTIAL, subgoals=sgs))
        types = {n.node_type for n in nodes}
        wf_str = (wf_type.value if len(types) <= 1 else "mixed")
        return WorkflowPlan(
            task_id=(task.task_id if task else ""), nodes=nodes,
            workflow_type=wf_str, generated_by="deterministic")

    def _classify_workflow(self, events: list[UserBehaviorEvent],
                           task: "CanonicalTaskGraph | None",
                           ) -> WorkflowNodeType:
        """FF.4 §5.3 rules (deterministic, zero LLM, zero latency):
          - any ``loop_field`` event → LOOP
          - exactly 1 ``edit_field`` whose binding fans out to ≥2 apps → PARALLEL
          - else SEQUENTIAL
        Mirrors structured-program shape detection (handoff §5.1)."""
        if any(ev.event_type == "loop_field" for ev in events):
            return WorkflowNodeType.LOOP
        edit_events = [ev for ev in events if ev.event_type == "edit_field"]
        if len(edit_events) == 1 and task is not None:
            var_id = edit_events[0].payload.get("var_id", "")
            apps = {b.app for b in task.bindings if b.var_id == var_id}
            if len(apps) >= 2:
                return WorkflowNodeType.PARALLEL
        return WorkflowNodeType.SEQUENTIAL

    def _interpret_loop_field(self, event: UserBehaviorEvent,
                              vm_state: VMStateSnapshot,
                              task: "CanonicalTaskGraph | None",
                              ) -> list[SubgoalInstruction]:
        """FF.4 §5.3: build the TEMPLATE subgoal for a loop_field event. The
        template's patch_op carries the binding's (first) entity_id as the
        placeholder; the WorkflowExecutor instantiates it per ``loop_values[i]``
        (substituting entity_id). The write value (e.g. "Bob") comes from
        payload['new_value'] or the task's user_edit['new']. The verification
        criterion is the task's full expected_diff (all loop entities — E11:
        each iteration is independently checked by the verifier)."""
        payload = event.payload
        var_id = payload.get("var_id", "")
        if not var_id:
            raise ValueError("loop_field event requires payload['var_id']")
        new_value = payload.get("new_value")
        if new_value is None and task is not None:
            new_value = task.user_edit.get("new")
        if new_value is None:
            new_value = ""
        values = list(payload.get("values", []))
        edit = {"var_id": var_id, "old": payload.get("old_value", ""),
                "new": new_value}
        ops = compile_patch(edit, vm_state.binding)
        criterion = task.expected_diff if task else {}
        # GG: translate loop_values (entity_ids) → visible titles for the NL.
        # The template op's first entity's app gives the canonical source.
        loop_app = ops[0].app if ops else (task.bindings[0].app if (task and task.bindings) else "")
        canonical_entities = self._canonical_for_op(
            PatchOp(app=loop_app, entity_id="", field="", operator="", value=""),
            vm_state) if loop_app else {}
        visible_values = []
        for v in values:
            loc = entity_id_to_locator(loop_app, v, canonical_entities)
            visible_values.append(loc if loc else "(an item)")
        # the var's user-facing label (not the internal var_id snake_case) if the
        # binding carries one
        var_label = var_id
        for var in (vm_state.binding.variables or []):
            if var.get("var_id") == var_id:
                var_label = var.get("label") or var_id
                break
        visible_list = "; ".join(visible_values) if visible_values else "each listed item"
        return [SubgoalInstruction(
            natural_language=(f"Batch operation — for each of these visible "
                              f"items ({visible_list}), set {var_label} to "
                              f"{new_value!r}. Use the UI to apply the change "
                              f"to each item in turn. Output "
                              f'{{"action":"done"}} when all reflect the new value.'),
            patch_ops=ops, verification_criterion=criterion,
            source_event_type="loop_field",
            meta={"loop_values": values, "loop_count": len(values)})]

    # ── set_milestone (advance toward a checkpoint) ───────────────────────
    def _interpret_set_milestone(self, event: UserBehaviorEvent,
                                 vm_state: VMStateSnapshot,
                                 task: "CanonicalTaskGraph | None",
                                 ) -> list[SubgoalInstruction]:
        """Advance from the current state to the target milestone. For now this
        is equivalent to edit_field with the target checkpoint's final value —
        a full milestone-graph advance (multi-step) is W-future. The target
        checkpoint id is taken from the payload."""
        target_cp = event.payload.get("target_checkpoint_id")
        if not target_cp or not task:
            raise ValueError("set_milestone requires target_checkpoint_id + task")
        graph = CheckpointGraph.from_task(task.checkpoints)
        criterion = graph.criterion_for(target_cp) or {}
        # the milestone's criterion IS the verification; the NL asks the CUA to
        # reach the state described by the criterion (the evaluation's executor
        # resolves the concrete ops from the binding).
        nl = (f"Advance the task to milestone {target_cp}: reach the state "
              f"described by {criterion}.")
        return [SubgoalInstruction(
            natural_language=nl, patch_ops=[],
            verification_criterion=criterion,
            source_event_type="set_milestone",
            target_checkpoint_id=target_cp,
        )]

    # ── rollback_to (dynamic LLM NL + deterministic undo_saga execution) ──
    def _interpret_rollback_to(self, event: UserBehaviorEvent,
                               vm_state: VMStateSnapshot,
                               task: "CanonicalTaskGraph | None",
                               ) -> list[SubgoalInstruction]:
        target_cp = event.payload.get("target_checkpoint_id", "C0")
        sagas = vm_state.sagas_after_checkpoint(target_cp)
        if not sagas:
            # nothing to undo — record honestly (no fake undo)
            return [SubgoalInstruction(
                natural_language=(f"Rollback to {target_cp}: no active sagas "
                                  f"to undo (already at or before this checkpoint)."),
                patch_ops=[], verification_criterion={},
                source_event_type="rollback_to",
                target_checkpoint_id=target_cp,
                meta={"n_sagas_undone": 0})]
        # NL description: dynamic LLM (strategy B) or deterministic template
        if self.enable_llm_rollback_nl:
            nl, llm_ok = self._infer_rollback_nl(target_cp, sagas, vm_state, task)
            llm_generated = llm_ok
        else:
            nl = (f"Roll back to checkpoint {target_cp} by undoing "
                  f"{len(sagas)} saga(s): {sagas}.")
            llm_generated = False
        # first-run LLM output → manual review (handoff §6 boundary 3)
        manual_review = llm_generated and self._rollback_nl_seen < 1
        if llm_generated:
            self._rollback_nl_seen += 1
        # execution is undo_saga (deterministic) — the subgoal records the
        # intent; the evaluation's executor calls undo_saga and attaches the
        # SagaResult to meta. We do NOT call undo_saga here (no sid/adapters
        # execution side-effect inside the interpreter — interpretation is pure
        # planning; execution happens in the evaluation's driver loop).
        graph = CheckpointGraph.from_task(task.checkpoints) if task else None
        criterion = graph.criterion_for(target_cp) if graph else {}
        subgoals: list[SubgoalInstruction] = []
        for saga_id in sagas:
            subgoals.append(SubgoalInstruction(
                natural_language=nl,
                patch_ops=[],
                verification_criterion=criterion,
                source_event_type="rollback_to",
                target_checkpoint_id=target_cp,
                saga_id=saga_id,
                llm_generated=llm_generated,
                manual_review_needed=manual_review,
                meta={"n_sagas_to_undo": len(sagas), "all_sagas": sagas},
            ))
        return subgoals

    def _infer_rollback_nl(self, target_cp: str, sagas: list[str],
                           vm_state: VMStateSnapshot,
                           task: "CanonicalTaskGraph | None",
                           ) -> tuple[str, bool]:
        """Dynamic LLM inference (handoff §1.3 strategy B): generate a
        natural-language description of what rolling back to ``target_cp``
        will undo, given the executed-ops log. Returns (nl, llm_ok). On any
        failure, falls back to a deterministic template (llm_ok=False)."""
        # build a description of the executed ops for the LLM (NO GT values —
        # only app/entity_id/field/operator, which are the binding, not GT)
        ops_desc = []
        for rec in vm_state.rollback_log.records:
            if rec.saga_id in sagas:
                ops_desc.append({"app": rec.app, "entity_id": rec.entity_id,
                                 "field": rec.field, "operator": rec.operator,
                                 "saga_id": rec.saga_id})
        system = (
            "You are a governance layer that translates a user's rollback "
            "intent into a concise natural-language description of what will "
            "be undone. You do NOT execute anything — you only describe. "
            "Respond with ONLY valid JSON: {\"description\": \"<one sentence>\"}.")
        user = (f"The user wants to roll back to checkpoint {target_cp}. "
                f"This requires undoing {len(sagas)} saga(s): {sagas}. "
                f"The executed operations to undo are: {ops_desc}. "
                f"Describe in one sentence what will be undone. Note: for "
                f"wechat send_message, undo is HONESTLY IRREVERSIBLE (the "
                f"adapter will raise 409 — do not claim it can be undone).")
        try:
            from taskvm.benchmark.model_client import complete_json
            parsed, _raw, _resp = complete_json(
                system=system, user=user, max_tokens=256,
                temperature=None, model=self.model, repair_retries=1)
            if isinstance(parsed, dict) and parsed.get("description"):
                return str(parsed["description"]), True
            return (f"Roll back to {target_cp}: undo {len(sagas)} saga(s) "
                    f"({sagas})."), False
        except Exception as e:
            logger.warning("rollback NL LLM inference failed (%s); "
                           "falling back to deterministic template", e)
            return (f"Roll back to {target_cp}: undo {len(sagas)} saga(s) "
                    f"({sagas})."), False

    # ── checkpoint (record snapshot — no execution) ───────────────────────
    def _interpret_checkpoint(self, event: UserBehaviorEvent,
                              vm_state: VMStateSnapshot) -> list[SubgoalInstruction]:
        """A checkpoint event records the current state. The evaluation's
        executor takes the canonical_snapshot and appends to
        vm_state.recorded_checkpoints + updates checkpoint_saga_map. The
        subgoal itself is a no-op marker (no CUA work)."""
        latest_saga = None
        if vm_state.rollback_log.records:
            latest_saga = vm_state.rollback_log.records[-1].saga_id
        return [SubgoalInstruction(
            natural_language="(checkpoint — record current state)",
            patch_ops=[], verification_criterion={},
            source_event_type="checkpoint",
            meta={"latest_saga_at_checkpoint": latest_saga})]

    # ── undo (per-app, existing verb) ─────────────────────────────────────
    def _interpret_undo(self, event: UserBehaviorEvent,
                        vm_state: VMStateSnapshot) -> list[SubgoalInstruction]:
        app = event.payload.get("app", "")
        if not app:
            raise ValueError("undo event requires payload['app']")
        saga_id = vm_state.rollback_log.latest_saga_id_for_app(app)
        if not saga_id:
            return [SubgoalInstruction(
                natural_language=f"Undo {app}: no active saga for this app.",
                patch_ops=[], verification_criterion={},
                source_event_type="undo", saga_id=None,
                meta={"app": app, "n_sagas_undone": 0})]
        return [SubgoalInstruction(
            natural_language=(f"Undo the last {app} saga ({saga_id}) via "
                              f"undo_saga — re-dispatches the inverse op "
                              f"through the adapter (honest 409 for wechat)."),
            patch_ops=[], verification_criterion={},
            source_event_type="undo", saga_id=saga_id,
            meta={"app": app})]


# ── NL template builders ───────────────────────────────────────────────────
# GG.3: the old ``_build_edit_nl`` (per-operator if/elif that leaked entity_id
# via "find event {eid}" / "chat {eid}" / "perform {operator} on {eid}") is
# DELETED. All NL generation now goes through the SubgoalGenerator
# (governance.subgoal_generator.instruction_for_op), which builds a zero-
# internal-id, zero-operator-jargon NL from the visible locator. The MobileGym
# visible_token / contact_name payload hints are screen-visible text — they are
# folded into the visible_locator upstream by the driver, not handled by an
# operator if/elif here.


def _criterion_for_op(op: PatchOp, task: "CanonicalTaskGraph | None",
                      target_cp: str | None, new_value: Any) -> dict:
    """Build the STRUCTURED verification criterion for an op. Prefers the
    target checkpoint's criterion (if the event names one), else the task's
    expected_diff for this op's (app, entity_id, field), else a synthetic
    {app: {entity_id: {field: new_value}}}."""
    if task and target_cp:
        for cp in task.checkpoints:
            if cp.id == target_cp and cp.criterion:
                return cp.criterion
    if task:
        ed = task.expected_diff.get(op.app, {}).get(op.entity_id, {})
        if op.field in ed:
            return {op.app: {op.entity_id: {op.field: ed[op.field]}}}
    # synthetic fallback (the value the user intended — verifier-side)
    return {op.app: {op.entity_id: {op.field: new_value}}}
