"""``GovernanceInterpreter`` — L3, the behavior→subgoal translation (E17-B).

The single most important new module (handoff §1.3). It takes a
``UserBehaviorEvent`` (what the user did on the GenUI surface) + a
``VMStateSnapshot`` (current VM state) and produces a list of
``SubgoalInstruction`` (what the CUA should execute + how to verify it).

Two translation strategies (handoff §1.3):
  - ``edit_field`` (deterministic): compile_patch(edit, binding) → PatchOps →
    one subgoal per op. The NL is template-derived (per operator + app), using
    visible-content hints from the event payload (NOT GT post_ids). This is
    the "space" strategy — no LLM call, zero latency.
  - ``rollback_to`` (dynamic, strategy B): execution is ``undo_saga`` (the
    proven deterministic mechanism — re-dispatches the inverse op through the
    adapter; for wechat this honestly 409s). The NL DESCRIPTION of what will
    be undone is generated by a lightweight LLM (``complete_json``, non-vision)
    — this is the "time" strategy (handoff §1.3). First-run output is flagged
    ``manual_review_needed=True`` (handoff §6 boundary 3).

Honest design decision (resolved from recon area 7): ``verification_criterion``
is STRUCTURED (an expected_diff-shaped dict or a checkpoint criterion), NOT a
string. The existing verifier (``check_round_trip``) takes a fixture +
snapshots, not a string — a string criterion would be incompatible. The
governance killtest's criterion-checker consumes this structured dict.

No-leak boundary: the interpreter receives the user's edit intent (var_id,
new_value) — allowed. It must NOT receive GT old/expected values through the
event. ``verification_criterion`` IS verifier-side GT (consumed by the
verifier, never fed to the CUA prompt) — same boundary as ``expected_diff``.
"""
from __future__ import annotations

import logging
from typing import Any, TYPE_CHECKING

from taskvm.execution.patch_compiler import PatchOp, compile_patch
from taskvm.governance.subgoal import SubgoalInstruction
from taskvm.governance.user_behavior_driver import UserBehaviorEvent
from taskvm.governance.vm_state import VMStateSnapshot
from taskvm.governance.checkpoint_graph import CheckpointGraph, CheckpointDirection

if TYPE_CHECKING:
    from taskvm.benchmark.fixtures import CanonicalTaskGraph

logger = logging.getLogger(__name__)


class GovernanceInterpreter:
    """Translate UserBehaviorEvents into SubgoalInstructions (L3)."""

    def __init__(self, *, model: str | None = None,
                 enable_llm_rollback_nl: bool = True) -> None:
        """Args:
          model: the model id for the dynamic rollback NL inference (None →
            TASKVM_DEFAULT_MODEL). Pass a cheaper id for the 'lightweight LLM'
            the handoff describes.
          enable_llm_rollback_nl: if False, skip the LLM call and use a
            deterministic NL template for rollback_to (for mock/offline runs).
        """
        self.model = model
        self.enable_llm_rollback_nl = enable_llm_rollback_nl
        self._rollback_nl_seen = 0  # count of LLM-generated rollback NLs (for manual-review flagging)

    # ── main entry ────────────────────────────────────────────────────────
    def interpret(self, event: UserBehaviorEvent,
                  vm_state: VMStateSnapshot,
                  *, task: "CanonicalTaskGraph | None" = None,
                  ) -> list[SubgoalInstruction]:
        """Event + VM state → subgoal list. The ``task`` arg (optional) gives
        the interpreter access to the fixture's checkpoints + expected_diff
        for verification-criterion construction. The scripted + human drivers
        both pass through here transparently."""
        if event.event_type == "edit_field":
            return self._interpret_edit_field(event, vm_state, task)
        if event.event_type in ("set_milestone",):
            return self._interpret_set_milestone(event, vm_state, task)
        if event.event_type == "rollback_to":
            return self._interpret_rollback_to(event, vm_state, task)
        if event.event_type == "checkpoint":
            return self._interpret_checkpoint(event, vm_state)
        if event.event_type == "undo":
            return self._interpret_undo(event, vm_state)
        # should not reach (UserBehaviorEvent validates event_type)
        raise ValueError(f"unhandled event_type {event.event_type!r}")

    # ── edit_field (deterministic) ────────────────────────────────────────
    def _interpret_edit_field(self, event: UserBehaviorEvent,
                              vm_state: VMStateSnapshot,
                              task: "CanonicalTaskGraph | None",
                              ) -> list[SubgoalInstruction]:
        payload = event.payload
        var_id = payload.get("var_id", "")
        new_value = payload.get("new_value", "")
        target_cp = payload.get("target_checkpoint_id")
        if not var_id:
            raise ValueError("edit_field event requires payload['var_id']")
        edit = {"var_id": var_id, "old": payload.get("old_value", ""),
                "new": new_value}
        ops = compile_patch(edit, vm_state.binding)
        subgoals: list[SubgoalInstruction] = []
        for op in ops:
            nl = _build_edit_nl(op, payload)
            criterion = _criterion_for_op(op, task, target_cp, new_value)
            subgoals.append(SubgoalInstruction(
                natural_language=nl,
                patch_ops=[op],
                verification_criterion=criterion,
                source_event_type="edit_field",
                target_checkpoint_id=target_cp,
            ))
        if not subgoals:
            logger.warning("edit_field produced no patch ops for var_id=%s", var_id)
        return subgoals

    # ── set_milestone (advance toward a checkpoint) ───────────────────────
    def _interpret_set_milestone(self, event: UserBehaviorEvent,
                                 vm_state: VMStateSnapshot,
                                 task: "CanonicalTaskGraph | None",
                                 ) -> list[SubgoalInstruction]:
        """Advance from the current state to the target milestone. For now this
        is equivalent to edit_field with the target checkpoint's final value —
        a full milestone-graph advance (multi-step) is W-future. The target
        checkpoint id is taken from the payload."""
        target_cp = event.payload.get("target_checkpoint_id")
        if not target_cp or not task:
            raise ValueError("set_milestone requires target_checkpoint_id + task")
        graph = CheckpointGraph.from_task(task.checkpoints)
        criterion = graph.criterion_for(target_cp) or {}
        # the milestone's criterion IS the verification; the NL asks the CUA to
        # reach the state described by the criterion (the killtest's executor
        # resolves the concrete ops from the binding).
        nl = (f"Advance the task to milestone {target_cp}: reach the state "
              f"described by {criterion}.")
        return [SubgoalInstruction(
            natural_language=nl, patch_ops=[],
            verification_criterion=criterion,
            source_event_type="set_milestone",
            target_checkpoint_id=target_cp,
        )]

    # ── rollback_to (dynamic LLM NL + deterministic undo_saga execution) ──
    def _interpret_rollback_to(self, event: UserBehaviorEvent,
                               vm_state: VMStateSnapshot,
                               task: "CanonicalTaskGraph | None",
                               ) -> list[SubgoalInstruction]:
        target_cp = event.payload.get("target_checkpoint_id", "C0")
        sagas = vm_state.sagas_after_checkpoint(target_cp)
        if not sagas:
            # nothing to undo — record honestly (no fake undo)
            return [SubgoalInstruction(
                natural_language=(f"Rollback to {target_cp}: no active sagas "
                                  f"to undo (already at or before this checkpoint)."),
                patch_ops=[], verification_criterion={},
                source_event_type="rollback_to",
                target_checkpoint_id=target_cp,
                meta={"n_sagas_undone": 0})]
        # NL description: dynamic LLM (strategy B) or deterministic template
        if self.enable_llm_rollback_nl:
            nl, llm_ok = self._infer_rollback_nl(target_cp, sagas, vm_state, task)
            llm_generated = llm_ok
        else:
            nl = (f"Roll back to checkpoint {target_cp} by undoing "
                  f"{len(sagas)} saga(s): {sagas}.")
            llm_generated = False
        # first-run LLM output → manual review (handoff §6 boundary 3)
        manual_review = llm_generated and self._rollback_nl_seen < 1
        if llm_generated:
            self._rollback_nl_seen += 1
        # execution is undo_saga (deterministic) — the subgoal records the
        # intent; the killtest's executor calls undo_saga and attaches the
        # SagaResult to meta. We do NOT call undo_saga here (no sid/adapters
        # execution side-effect inside the interpreter — interpretation is pure
        # planning; execution happens in the killtest's driver loop).
        graph = CheckpointGraph.from_task(task.checkpoints) if task else None
        criterion = graph.criterion_for(target_cp) if graph else {}
        subgoals: list[SubgoalInstruction] = []
        for saga_id in sagas:
            subgoals.append(SubgoalInstruction(
                natural_language=nl,
                patch_ops=[],
                verification_criterion=criterion,
                source_event_type="rollback_to",
                target_checkpoint_id=target_cp,
                saga_id=saga_id,
                llm_generated=llm_generated,
                manual_review_needed=manual_review,
                meta={"n_sagas_to_undo": len(sagas), "all_sagas": sagas},
            ))
        return subgoals

    def _infer_rollback_nl(self, target_cp: str, sagas: list[str],
                           vm_state: VMStateSnapshot,
                           task: "CanonicalTaskGraph | None",
                           ) -> tuple[str, bool]:
        """Dynamic LLM inference (handoff §1.3 strategy B): generate a
        natural-language description of what rolling back to ``target_cp``
        will undo, given the executed-ops log. Returns (nl, llm_ok). On any
        failure, falls back to a deterministic template (llm_ok=False)."""
        # build a description of the executed ops for the LLM (NO GT values —
        # only app/entity_id/field/operator, which are the binding, not GT)
        ops_desc = []
        for rec in vm_state.rollback_log.records:
            if rec.saga_id in sagas:
                ops_desc.append({"app": rec.app, "entity_id": rec.entity_id,
                                 "field": rec.field, "operator": rec.operator,
                                 "saga_id": rec.saga_id})
        system = (
            "You are a governance layer that translates a user's rollback "
            "intent into a concise natural-language description of what will "
            "be undone. You do NOT execute anything — you only describe. "
            "Respond with ONLY valid JSON: {\"description\": \"<one sentence>\"}.")
        user = (f"The user wants to roll back to checkpoint {target_cp}. "
                f"This requires undoing {len(sagas)} saga(s): {sagas}. "
                f"The executed operations to undo are: {ops_desc}. "
                f"Describe in one sentence what will be undone. Note: for "
                f"wechat send_message, undo is HONESTLY IRREVERSIBLE (the "
                f"adapter will raise 409 — do not claim it can be undone).")
        try:
            from taskvm.benchmark.model_client import complete_json
            parsed, _raw, _resp = complete_json(
                system=system, user=user, max_tokens=256,
                temperature=None, model=self.model, repair_retries=1)
            if isinstance(parsed, dict) and parsed.get("description"):
                return str(parsed["description"]), True
            return (f"Roll back to {target_cp}: undo {len(sagas)} saga(s) "
                    f"({sagas})."), False
        except Exception as e:
            logger.warning("rollback NL LLM inference failed (%s); "
                           "falling back to deterministic template", e)
            return (f"Roll back to {target_cp}: undo {len(sagas)} saga(s) "
                    f"({sagas})."), False

    # ── checkpoint (record snapshot — no execution) ───────────────────────
    def _interpret_checkpoint(self, event: UserBehaviorEvent,
                              vm_state: VMStateSnapshot) -> list[SubgoalInstruction]:
        """A checkpoint event records the current state. The killtest's
        executor takes the canonical_snapshot and appends to
        vm_state.recorded_checkpoints + updates checkpoint_saga_map. The
        subgoal itself is a no-op marker (no CUA work)."""
        latest_saga = None
        if vm_state.rollback_log.records:
            latest_saga = vm_state.rollback_log.records[-1].saga_id
        return [SubgoalInstruction(
            natural_language="(checkpoint — record current state)",
            patch_ops=[], verification_criterion={},
            source_event_type="checkpoint",
            meta={"latest_saga_at_checkpoint": latest_saga})]

    # ── undo (per-app, existing verb) ─────────────────────────────────────
    def _interpret_undo(self, event: UserBehaviorEvent,
                        vm_state: VMStateSnapshot) -> list[SubgoalInstruction]:
        app = event.payload.get("app", "")
        if not app:
            raise ValueError("undo event requires payload['app']")
        saga_id = vm_state.rollback_log.latest_saga_id_for_app(app)
        if not saga_id:
            return [SubgoalInstruction(
                natural_language=f"Undo {app}: no active saga for this app.",
                patch_ops=[], verification_criterion={},
                source_event_type="undo", saga_id=None,
                meta={"app": app, "n_sagas_undone": 0})]
        return [SubgoalInstruction(
            natural_language=(f"Undo the last {app} saga ({saga_id}) via "
                              f"undo_saga — re-dispatches the inverse op "
                              f"through the adapter (honest 409 for wechat)."),
            patch_ops=[], verification_criterion={},
            source_event_type="undo", saga_id=saga_id,
            meta={"app": app})]


# ── NL template builders (deterministic, per operator + app) ───────────────
def _build_edit_nl(op: PatchOp, payload: dict) -> str:
    """Build a goal-level NL instruction for a PatchOp, using visible-content
    hints from the event payload (NOT GT post_ids). The payload may carry:
      - visible_token: visible text identifying the target (MG-1 visible-
        uniqueness path — the token is on-screen, not a backdoor).
      - contact_name: the wechat contact's display name.
      - message_text: the text to type/send.
    """
    app, eid, field, operator, value = op.app, op.entity_id, op.field, op.operator, op.value
    visible_token = payload.get("visible_token")
    contact_name = payload.get("contact_name")
    if operator == "toggle_like":
        if visible_token:
            return (f"On the X (Twitter) app timeline, find the post containing "
                    f"the text \"{visible_token}\" and tap the heart (like) icon "
                    f"in its action bar so it becomes filled/active. "
                    f"Output {{\"action\":\"done\"}} once the heart is filled. "
                    f"If you cannot find that post, output "
                    f"{{\"action\":\"fail\",\"reason\":\"...\"}}.")
        return (f"On the X app timeline, find a post whose heart (like) icon is "
                f"not yet filled and tap it. Output {{\"action\":\"done\"}} when done.")
    if operator == "toggle_retweet":
        return (f"On the X app timeline, find a post whose repost icon is not "
                f"yet active and tap it. Output {{\"action\":\"done\"}} when done.")
    if operator == "toggle_bookmark":
        return (f"On the X app timeline, find a post whose bookmark icon is not "
                f"yet active and tap it. Output {{\"action\":\"done\"}} when done.")
    if operator == "send_message":
        who = contact_name or f"chat {eid}"
        text = value if isinstance(value, str) else str(value)
        return (f"In the WeChat app, open the chat with {who}, type exactly: "
                f"\"{text}\", and send it. Output {{\"action\":\"done\"}} once "
                f"the message is sent.")
    if operator == "move_event":
        return (f"In the calendar app, find event {eid} and change its {field} "
                f"to {value}. Output {{\"action\":\"done\"}} when done.")
    if operator == "set_deadline":
        return (f"In the task board app, find task {eid} and change its "
                f"{field} to {value}. Output {{\"action\":\"done\"}} when done.")
    if operator == "set_status":
        return (f"In the task board app, find task {eid} and set its "
                f"{field} to {value}. Output {{\"action\":\"done\"}} when done.")
    if operator == "move_file":
        return (f"In the drive app, find file {eid} and move it to the "
                f"{value} folder. Output {{\"action\":\"done\"}} when done.")
    if operator == "rename":
        return (f"In the drive app, find file {eid} and rename it to "
                f"{value}. Output {{\"action\":\"done\"}} when done.")
    # generic fallback
    return (f"In the {app} app, perform {operator} on {eid} field {field} "
            f"→ {value}. Output {{\"action\":\"done\"}} when done.")


def _criterion_for_op(op: PatchOp, task: "CanonicalTaskGraph | None",
                      target_cp: str | None, new_value: Any) -> dict:
    """Build the STRUCTURED verification criterion for an op. Prefers the
    target checkpoint's criterion (if the event names one), else the task's
    expected_diff for this op's (app, entity_id, field), else a synthetic
    {app: {entity_id: {field: new_value}}}."""
    if task and target_cp:
        for cp in task.checkpoints:
            if cp.id == target_cp and cp.criterion:
                return cp.criterion
    if task:
        ed = task.expected_diff.get(op.app, {}).get(op.entity_id, {})
        if op.field in ed:
            return {op.app: {op.entity_id: {op.field: ed[op.field]}}}
    # synthetic fallback (the value the user intended — verifier-side)
    return {op.app: {op.entity_id: {op.field: new_value}}}
